### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by AnthonyF333** [pshashk/seesaw-facenet#1]
Great work @pshashk ! Which training data did you use to train the network?

**Comment by pshashk** [comment]
Thanks! Dataset is the same one used in the paper (MS1MV2). Can be obtained from [InsightFace Dataset Zoo](https://github.com/deepinsight/insightface/wiki/Dataset-Zoo#ms1m-arcface-85k-ids58m-images-57-recommend)

**Comment by AnthonyF333** [comment]
OK, thanks a lot!
