### ISSUE TITLE
Activation function

### ISSUE THREAD

**Issue by AnthonyF333** [pshashk/seesaw-facenet#2]
Hello @pshashk, thanks for your great job. 
I want to know why the first two conv are followed by relu, but the other conv are followed by hswish. Are there some tricks on it?

**Comment by pshashk** [comment]
Hello @tankrant 
Thanks
It's similar to the way [mobilenet V3](https://arxiv.org/abs/1905.02244) mixes the different activations.

**Comment by AnthonyF333** [comment]
Thanks a lot! I get it.
